# printWidth: 80
# tabWidth: 2
# useTabs: false
semi: false # true
# singleQuote: false
# jsxSingleQuote: false
trailingComma: "all" # "none"
# bracketSpacing: true
# jsxBracketSameLine: false
# arrowParens: "avoid"
# rangeStart: 0
# rangeEnd: Infinity
# parser: None
# filepath: None
# requirePragma: false
# insertPragma: false
# proseWrap: "preserve"
# htmlWhitespaceSensitivity: "css"
# endOfLine: "auto"